# This file contains values from Cookiecutter

default_context:
  project_name: "echo_journey"
  project_description: "echo_journey is all your need"
  organization: "kanyun"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "yuniuniuniu"
  email: "544569390@qq.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
