# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: upward.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cupward.proto\x12\x13\x65\x63ho_journey.upward\"V\n\rUpwardMessage\x12\x34\n\x04type\x18\x01 \x01(\x0e\x32&.echo_journey.upward.UpwardMessageType\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\"\x1e\n\x0eStudentMessage\x12\x0c\n\x04text\x18\x01 \x01(\t\"=\n\x0c\x41udioMessage\x12\x19\n\x11\x65xpected_sentence\x18\x01 \x01(\t\x12\x12\n\naudio_data\x18\x02 \x01(\x0c*H\n\x11UpwardMessageType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x13\n\x0fSTUDENT_MESSAGE\x10\x01\x12\x11\n\rAUDIO_MESSAGE\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'upward_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPWARDMESSAGETYPE']._serialized_start=220
  _globals['_UPWARDMESSAGETYPE']._serialized_end=292
  _globals['_UPWARDMESSAGE']._serialized_start=37
  _globals['_UPWARDMESSAGE']._serialized_end=123
  _globals['_STUDENTMESSAGE']._serialized_start=125
  _globals['_STUDENTMESSAGE']._serialized_end=155
  _globals['_AUDIOMESSAGE']._serialized_start=157
  _globals['_AUDIOMESSAGE']._serialized_end=218
# @@protoc_insertion_point(module_scope)
